services:
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./server:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
  gui:
    restart: unless-stopped
    build:
      context: ../gui
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
  api:
    restart: unless-stopped
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "3021:3021"

volumes:
  caddy_data:
  caddy_config:
