services:
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  # gui:
  #   build:
  #     context: ../gui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3020:3020"

volumes:
  caddy_data:
  caddy_config:
